### ISSUE TITLE
Unless you're just doing it for clarity, winningLine is redundant in getResult

### ISSUE THREAD

**Issue by jbmonroe** [carpben/TicTacToe#3]
Since _winningLine_ doesn't need to survive until the end of the function, declaring it and then returning immediately has to be for the purpose of making a rhetorical point, not actual code efficiency.  Am I right?

**Comment by carpben** [comment]
I don't completely understand the question. 
'winningLine' is declared on line 79. Then it is used in the various for loops starting on line 82. If a winning line is found, values are pushed into the 'winningLine' var which is then returned. 
You might be asking why do I declare it before the for loops. Since the use of winningLine is nested in a condition it might not be used at all. In this sense you are correct. I think the code is more clear this way. I could have nested the var decleration nested in the condition where it's used, but then I'd have to do it multiple times.

**Comment by jbmonroe** [comment]
Okay, I'll look at that again.  I looked at it a couple of times and it looked like it was just assigned for the purpose of being returned.

**Comment by jbmonroe** [comment]
Okay, here's what I see:
```

      //first we check row, then column, then diagonal
      for (var i = 0 ; i<3 ; i++){
        line = board[i].join('')
        if(succession(line)){
          result = symbol;
          winningLine = [[i,0], [i,1], [i,2]]
          return {result, winningLine};
        }
      }
```

Except, it should be

```
      //first we check row, then column, then diagonal
      for (var i = 0 ; i<3 ; i++){
        line = board[i].join('')
        if(succession(line)){
          result = symbol;
          return {result, [[i,0], [i,1], [i,2]]};
        }
      }

```
In the check-for-tie code, _winningLine_ simply returns its initialized value, so you could have just written

`return {result, []}`

The return at the coda doesn't use _winningLine_ at all.  Any assignment of a non-empty array value to _winningLine_ is immediately followed by a return, so assigning it has no value.  The literal can be returned directly at any of those points with no loss of clarity.   I conclude, therefore, that _winningLine_ is completely redundant.

**Comment by carpben** [comment]
I programmed the whole game a few months ago, and I might have done things differently today. 

As for your suggestion: 
` return {result, [[i,0], [i,1], [i,2]]};`
compare it to my line: 
'return {result, winningLine};'
I find the latter to be much more clean, and easy to read, both for another programmer and for future self. 
Returning 'return {result, [[i,0], [i,1], [i,2]]};' might be negligibly more efficient (if at all), but is less clear and less structured. The same goes for 'return {result, []}'
This The purpose of the winningLine var is to allow the render function, and more specifically the htmlGameEnd to color the winning symbols. We need it only when the game ends. The coda is for cases in which the game is incomplete. In such cases we don't need the winningLine var.

**Comment by carpben** [comment]
You are right, I'm using it for clarity.

**Comment by jbmonroe** [comment]
Since the values aren't computed, they'd have done perfectly well as
constants, which gives clarity and allows them to be generated only once.
It's a matter of taste, I suppose.  I submit that after 40 years of
programming I have particular tastes. :)

**Comment by carpben** [comment]
Well, I have what to learn from you... 
Didn't know you had such an experience... 
:-)

**Comment by jbmonroe** [comment]
You live this long, you learn things.  And then you start to forget them. :)

I like that you're writing these articles and publishing code--I wish I had
the time.
