### ISSUE TITLE
It's impossible to win against the computer

### ISSUE THREAD

**Issue by emilas44** [carpben/TicTacToe#5]
The best that a user can achieve is a Tie.

**Comment by carpben** [comment]
That's right. The computer player was designed to optimize its' own moves.  The result is that the person that plays against it can only achieve a tie.

**Comment by sambidsresh** [comment]
Tic-Tac-Toe is a relatively simplistic game. If both players have a little experience. A tie is all that can be achieved. The program has been optimized to the degree that it is impossible to win.
